# Generated by Django 5.0.6 on 2024-07-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibraryaccount',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
